### PR TITLE
flow autocomplete takes content from stdin instead of from a file.

### PR DESCRIPTION
**Pull request by shiqicao**

### CODE REVIEW

**Comment by aaronjensen** [comment]
@shiqicao Could you please tell me what version of flow you're using and what issue you are seeing? The way it is is correct, and works for me. See help:

```
$ flow autocomplete --help
Usage: flow autocomplete [OPTION] [FILE] [LINE COLUMN]...

Queries autocompletion information.

If line and column is specified, then the magic autocomplete token is
automatically inserted at the specified position.

Example usage:
        flow autocomplete < foo.js
        flow autocomplete path/to/foo.js < foo.js
        flow autocomplete 12 35 < foo.js

  --from                            Specify client (for use by editor plugins)
  --help                            This list of options
  --ignore-version                  Ignore the version constraint in .flowconfig
  --json                            Output results in JSON format
  --no-auto-start                   If the server is not running, do not start it; just exit
  --pretty                          Pretty-print JSON output (implies --json)
  --quiet                           Suppress output about server startup
  --retries                         Set the number of retries. (default: 3)
  --retry-if-init                   retry if the server is initializing (default: true)
  --root                            Project root directory containing the .flowconfig
  --sharedmemory-dep-table-pow      The exponent for the size of the shared memory dependency table. The default is 17, implying a size of 2^17 bytes
  --sharedmemory-dirs               Directory in which to store shared memory heap (default: /dev/shm/)
  --sharedmemory-hash-table-pow     The exponent for the size of the shared memory hash table. The default is 19, implying a size of 2^19 bytes
  --sharedmemory-log-level          The logging level for shared memory statistics. 0=none, 1=some
  --sharedmemory-minimum-available  Flow will only use a filesystem for shared memory if it has at least these many bytes available (default: 536870912 - which is 512MB)
  --strip-root                      Print paths without the root
  --temp-dir                        Directory in which to store temp files (default: /tmp/flow/)
  --timeout                         Maximum time to wait, in seconds
```

**Comment by shiqicao** [comment]
@aaronjensen the version is 0.37.4
1. In Example usage, it takes from stdin
2. Usually autocompletion is triggered before a file save, so it's reasonable that it shouldn't take content from a file.

**Comment by aaronjensen** [comment]
Hi @shiqicao

> 1. In Example usage, it takes from stdin

 stdin is required and company-flow sends the buffer via stdin [here](https://github.com/aaronjensen/company-flow/blob/1f10d38135679f705494f23cd866ded0130e2993/company-flow.el#L110)

flow uses the optional file argument to know where the file is that is being supplied via stdin is so that it can find the `.flowconfig` and so that it can properly resolve relative requires and imports.

> 2. Usually autocompletion is triggered before a file save, so it's reasonable that it shouldn't take content from a file.

This is true, and I do not believe flow uses the file for anything but location and locating the flowconfig.

Without it, it cannot properly resolve relative requires and imports, so, it is required for proper usage. The only time it would not be helpful is in a non-file-visiting buffer, but the prefix function return nil in those cases.

That said, I can see a problem with a buffer that is visiting a file that does not yet exist because it has never been saved. I'm [excluding those now](https://github.com/aaronjensen/company-flow/blob/1f10d38135679f705494f23cd866ded0130e2993/company-flow.el#L137) but it would be nice to support that. It would probably require us to use `--root` and point it to an existing directory that has a `.flowconfig`. Is that perhaps the problem you are having?

If not, please provide the error or incorrect behavior that you are seeing so that I can help you troubleshoot the problem you are running into. 

Thanks!

**Comment by aaronjensen** [comment]
I'm going to close this, if you're still having trouble please open a new issue.

Thanks!

**Pull request closed without merging**
